apiVersion: apps/v1
kind: Deployment
metadata:
  name: diabetes-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: diabetes-api
  template:
    metadata:
      labels:
        app: diabetes-api
    spec:
      containers:
      - name: mlops-fastapi
        image: us-central1-docker.pkg.dev/${PROJECT_ID}/mlops-test/mlops-fastapi:${IMAGE_TAG}
        ports:
        - containerPort: 8000
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: diabetes-api-service
spec:
  selector:
    app: diabetes-api
  ports:
  - port: 80
    targetPort: 8000
  type: LoadBalancer
